#index:
#    path: /
#    controller: App\Controller\DefaultController::index
display_image:
    path: '/event/front/{id}/image'
    controller: 'App\Controller\EventFrontController::displayImageAction'
    requirements:
        id: '\d+'
