#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_event_image:
    path: '/event/front/{idEv}/image'
    controller: 'App\Controller\EventFrontController::displayImageAction'
    requirements:
        idEv: '\d+'

